### ISSUE TITLE
Implementation Repo Changes

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/SpongeCommon#112]
Pinging @SpongePowered/developers 

This has been brewing internally for a bit but now we want to take the first steps at fixing up our repo setup so that it isn't so painful to work on the Sponge implementation. Here is what needs to happen (looking at you @Minecrell ). Any assistance you can add would be great @AbrarSyed .

1. Rename Sponge to SpongeForge. Only happens when the below is finished.
* Adjust classpath of SpongeVanilla to org.spongepowered.server. I do NOT want to rename SpongeForge's classpath as I don't want anyone confused about the fact it would become org.spongepowered.forge. Changing Vanilla's makes a lot more sense as SpongeVanilla is actually the full server modification (instead of being a mod for another one).
* Remove building of SpongeCommon in SpongeForge and SpongeVanilla. This, in lack of better words, turns SpongeCommon into just a sourceset in those projects. This will cut down the setupDecompWorkspaces to 1 per impl.
* SpongeForge and SpongeVanilla need to have the runDir added to their scripts (or perhaps to the common one) so that gradle runServer/runClient will have its root in the run directory.
* SpongeForge should remove the subfolders for server and client in its run directory. This is not needed whatsoever.
* Come up with a mechanism to handle the hassle with dealing with submodules. This is not an open invitation to some bastard "run a shell script and it will setup some symlinked workspace for you". I'm thinking of an optional thing to run (as part of the toolchain) that would not only update submodules but also do setupDecompWorkspace. I welcome ideas on this one.

I'm aware I said that we would merge back into one repo. After thinking about it and hearing both sides, it would fix some issues but bring about new ones that would go against the spirit of this project (and definitely against Vanilla).

At this point, this is higher priority than anything else on our plate.

---
### TODO

- [x] Update to ForgeGradle 2
  - [x] SpongeCommon
    - [x] Remove client code
  - [x] Sponge
    - [x] Add client code
  - [x] SpongeVanilla
- [x] Cleanup Gradle environment
- [x] ~~Add SpongeCommon as a sourceset~~
- [x] ~~Simplify submodules by integrating them into the build system~~
- [x] Move `org.spongepowered.vanilla` -> `org.spongepowered.server`
- [x] Rename `Sponge` -> `SpongeForge`

**Comment by zml2008** [comment]
(Updated main comment to use numbers for easier referencing)

So 3-5 can happen at any time without breaking PRs -- they're just build process tweaks
2 probably won't have much impact since there usually isn't much implementation-specific happening ever
6. Removing the hassle of dealing with submodules is why I wanted one repo in the first place -- it also reduces the overhead of contributing to both Vanilla and Forge implementations. However, if we go with separate repos, things like https://github.com/prezi/pride might help to reduce the difficulties -- things are split into separate repos but don't need the crazy submodule setup and 189382394834 'bump common ref' commits.

**Comment by Zidane** [comment]
After more discussion, @bloodmc put forth the idea of versioning common. This actually solves many issues:

Pros:

* We can target different versions of common in SpongeForge and SpongeVanilla (fixes lockstep)
* We can stop doing submodules altogether for the impl.
* We keep setupDecompWorkspace to a min (1 per impl, as was before).

Cons:

* Increased developer responsibility. Impl devs will need to be sure to bump the version when things break or an AT changes.

...and that's basically it. I've thought about it a lot and this is the smoothest way forward. It keeps things as simple as possible.

@SpongePowered/developers

**Comment by zml2008** [comment]
For folks working on common, that would be 3 total setupDecompWorkspaces, unless you could make gradle just depend on packaged sources or something (using common only as a source repo would be 2 SDWs).

However, this new method is fairly simple to set up -- @progwml6 has to get common set up to CI, then delete the submodules, and change the dependency spec. Only other change is to figure out how to manage the impl build files, which currently all import groovy files from common and API (which needs the submodule to work -- possibly another build-support project or something, dunno?)

**Comment by DarkArc** [comment]
Perhaps the arguments of both of the original sides (those who wish to see the repos merged, and those who do not) would be helpful in determining the best solution. 

> I'm aware I said that we would merge back into one repo. After thinking about it and hearing both sides, it would fix some issues but bring about new ones that would go against the spirit of this project (and definitely against Vanilla).

This is not helpful to anyone not completely familiar with the discussion. It is not clear what issues need to be solved, and what specifically has already been considered. I appreciate your time invested, but this discussion might as well remain entirely internal unless more information is provided, and referenced. 

> After more discussion, @bloodmc put forth the idea of versioning common.

So, I do not see a way in which this resolves any of what I consider to be the key issues here.

>     We can target different versions of common in SpongeForge and SpongeVanilla (fixes lockstep)

How is this any different from using a git submodule? Commits can be referenced in the same way "versions" of a jar can. 

>     We keep setupDecompWorkspace to a min (1 per impl, as was before).

As zml noted, if we're working on common and let's say the forge implementation. How would this be the case? If we're to be realistic the vast majority of the time if you're working on the Forge implementation, you're also going to need to touch common. 

Also, packaging the output of setupDecompWorkspace could land us in potentially shaky legal ground. One of the benefits of a forge style implementation is that we don't have to worry about packaging the actual minecraft code.

> However, if we go with separate repos, things like https://github.com/prezi/pride might help to reduce the difficulties -- things are split into separate repos but don't need the crazy submodule setup and 189382394834 'bump common ref' commits.

This is a more fleshed out implementation of what I was originally considering for a script based system, nice find zml. This is the only way I see sanity coming to a multi repo structure like this where the repos are arguably not self standing projects.

**Comment by Zidane** [comment]
@DarkArc 

...and to this day I've yet to see your script solution put onto paper and up for review. This issue was made so that team members could keep up to speed with what is going on AND community members can see that we are moving on solving this issue. This isn't like other projects, I don't keep things behind closed doors.

The problem you aren't getting with submodules is the gradle scripts handle dependencies and therefore is superior to git submodules because you don't have to hope that joe developer actually does a submodule update. The goal is to make this stupid simple.

**Comment by DarkArc** [comment]
#### Git submodule troubles

> The problem you aren't getting with submodules is the gradle scripts handle dependencies and therefore is superior to git submodules because you don't have to hope that joe developer actually does a submodule update. The goal is to make this stupid simple.

Well has using a git hook been considered? I'd have to test it to make sure, but this (or something like it) should work: 
https://github.com/chaitanyagupta/gitutils/blob/master/submodule-hooks/post-merge-checkout

The benefit here being, we don't have to invest time in converting the build system, nor concern ourselves with the extra bandwidth. 

Additionally, has it been considered that we could potentially add onto our gradle build task a git submodule update step? It's not impossible to work with git inside of gradle. 
http://stackoverflow.com/questions/13719676/gradle-how-to-clone-a-git-repo-in-a-task

The mentioned project doesn't currently appear to support submodules, however, it proves the concept of git integration into a gradle build procedure is more than possible.

One possibly interesting approach would be to grab the commit hash for both submodules, and match them to what should be checked out. This could allow us to set "tampered" flags which would reveal that the build may be invalid, as well as emit warnings.

#### Lack of my script solution

> ...and to this day I've yet to see your script solution put onto paper and up for review. This issue was made so that team members could keep up to speed with what is going on AND community members can see that we are moving on solving this issue. This isn't like other projects, I don't keep things behind closed doors.

I have a lot to do these days, sorry, but I'm not going to be able to put the time in to do it properly, and if I can't do it properly, I'm not going to do it. There's also a large amount of work and knowledge about the current gradle setup required to implement such a thing, both of which as previously noted I don't currently have time for. 

The attitudes towards a home brewed script solution were also far from enthusiastic. However, what zml has brought to the table, is not unique to Sponge, nor is it -- at least from the surface -- half baked.

As for hiding things behind closed doors, I don't see the point in having open contact with a community if you don't give them the means to partake in the discussion intelligently. I'm arguing that there should be more information here, not less. 

#### Core problems

Regardless of the above, I find distributing jars, or using submodules to be treating the symptom, not the root problem. Which in my opinion anyways, is that our source is divided into several different repositories, each with their own concept of a build system, and two different implementations.

One argument for separate repositories is that we can have people work on the API and the implementation. This is one of those things that sounds far better on paper than in practice. What good is an API definition without an implementation? 

Allowing this is like using the waterfall method. Rather than adapting the API as more is discovered about our implementation requirements, we're currently creating it up front. This approach has been proven to be flawed time and time again. How many things have been recoded in Sponge because we decided, "Oh hey that actually isn't going to be practical to implement?" or during implementation we discovered "oh... wait, this doesn't make as much sense as it originally did."

Following that conclusion, we hit another road block however when considering requiring an implementation, because at some point it was decided to officially on board Vanilla and Forge. So now we must maintain two implementations with separate bases. It seems unreasonable to require two different implementations with an API PR. 

So what can we do at this point? "Version stuff!" Great... Now we've just made the problem worse. We don't even know what features we have anymore. As @bloodmc has pointed out, the commit log is also not an accurate tale as we have "Bump common ref" with the jars, we'll undoubtedly have "Bump common version".

There is an abstraction @sk89q used in WorldEdit, platforms, which allows WorldEdit to query for features of the implementation. This is a far more reasonable approach, as it allows the implementation to say "I don't actually support that... please don't touch it..."

If we want to support things as a multi implementation API we should actually do that, rather than praying that somehow implementation A & B can be put into sync, and assuming everything API definition wise can be taken care of ahead of time.

Following this train of thought, also frees us from Bukkit's core limitation, which is backwards compatibly -- and thus refusing to accept API features that could at some point be removed. As with this methodology, you can write your plugin to respond to the lack of a feature, without causing crazy problems, and thus can add more fine grained APIs which leverage current features.
 
This is not pertinent to the discussion, however, I used to say "Bukkit is a mod, and it should act like such." Anything can be removed, and trying to determine the effectiveness of a modding API on the probably that a feature is not removed is a fundamental failure in my opinion.

**Comment by modwizcode** [comment]
Excellent analysis. I agree wholeheartedly with the final point.

**Comment by JBYoshi** [comment]
Some pros and cons of the various setups (just from what I've heard here and what I can think of off the top of my head):

#### Current setup
Pros:
- Forge and Vanilla can have separate common versions

Cons:
- Implementation developers have to work with separate repositories
- 1 `setupDecompWorkspace` per repository (common, Forge, vanilla)
- Lots of "bump common ref"s

#### Submodules, common as source set
Pros:
- Forge and Vanilla can have separate common versions
- 1 `setupDecompWorkspace` per implementation (Forge/vanilla)

Cons:
- Implementation developers have to work with separate repositories
- Lots of "bump common ref"s

#### Versioning
Pros:
- Forge and Vanilla can have separate common versions
- Not as many "bump common version"s, but still some

Cons:
- Implementation developers have to work with separate repositories
- Repositories aren't as tied together
- 1 `setupDecompWorkspace` per repository (common, Forge, and vanilla)

#### Single repository
Pros:
- No "bump common ref"s
- No confusion with symlinks
- 1 `setupDecompWorkspace` per implementation (Forge/vanilla), depending on the setup

Cons:
- Forge and vanilla have to have the same common version

**Comment by kenzierocks** [comment]
You missed what I think is the biggest con of submodules, and that's the difficulty for beginners. We need something that won't block people from helping. Additionally, we need an easy way to say which repo to pull from, so that PRs can be built by Travis.

**Comment by JBYoshi** [comment]
@kenzierocks Added.

**Comment by Zidane** [comment]
@JBYoshi 

Your current cons are incorrect. Doing a setupDecompWorkspace on Sponge or SpongeVanilla does a setupDecompWorkspace as well for its SpongeCommon. So it takes double time and therefore is 2 per impl.

**Comment by JBYoshi** [comment]
@Zidane Fixed.

**Comment by Zidane** [comment]
```
Allowing this is like using the waterfall method. Rather than adapting the API as more is discovered about our implementation requirements, we're currently creating it up front. This approach has been proven to be flawed time and time again. How many things have been recoded in Sponge because we decided, "Oh hey that actually isn't going to be practical to implement?" or during implementation we discovered "oh... wait, this doesn't make as much sense as it originally did."

Following that conclusion, we hit another road block however when considering requiring an implementation, because at some point it was decided to officially on board Vanilla and Forge. So now we must maintain two implementations with separate bases. It seems unreasonable to require two different implementations with an API PR. 
```

Couple of things @DarkArc .

* There was simply no way to write the Sponge impl first with building the API at the same time because the technology to do it correctly (Mixins) wasn't ready for at least 6 MONTHS after the project started. We wouldn't be where we are today so no.
* An API, just like any software, is an evolving construct. SpongeAPI will never be "finished" nor will the Sponge ecosystem. It will continue to evolve until no one is evolving it. This means things will get re-written. Speaking of things re-written, in actuality very little has been re-written because we purposedly staged out what was written for the API to be as generic as possible. The only thing that comes to mind when we talk re-writes would be the data API (but that was never complete to begin with...).
* The focus is and continues to be on the API and SpongeForge. While SpongeVanilla is its sister project, its more MY project and while I ask team members to update x, y, z in Vanilla, its ultimately me working on it.Given the choice, I'd rather people focus on SpongeCommon and SpongeForge; let me handle most if not all the work for SpongeVanilla (I know its code better than anyone anyhow).
* Almost all impl PRs will target common. Very few things need a separate impl based on Forge.

**Comment by DDoS** [comment]
This might be a stupid idea, but do we even need to build common? Is there any way of just having it as a source that gets included with the SpongeForge/Vanilla build?

**Comment by JBYoshi** [comment]
@DDoS That was part of the original idea (#3).

**Comment by progwml6** [comment]
My main concern relying on building common is that it will make pulling in PR's locally for testing difficult

**Comment by JBYoshi** [comment]
From what I've heard, you can just pull a hidden branch in the API and common repositories and just leave SpongeForge as is. See https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by progwml6** [comment]
@JBYoshi if we were relying on builds of common in the maven repo to build spongeforge/spongevanilla I think it might be difficult for the dev team to test the PR's

**Comment by JBYoshi** [comment]
I get it. Added.

**Comment by Zidane** [comment]
For @Minecrell 

In making these changes, please adjust the toolchain so that checkstyle runs dead last (and not before licenseFormat). Unless I'm badly mistaken, this is happening in reverse currently.

**Comment by Minecrell** [comment]
Ok, so the plan is to update the build environment to the new [ForgeGradle](https://github.com/MinecraftForge/ForgeGradle) version together with these changes. This will allow us to remove the [temporary Vanilla support Gradle plugin](https://github.com/Minecrell/VanillaGradle) we used up to now because [ForgeGradle 2](https://github.com/MinecraftForge/ForgeGradle/releases/tag/v2.0.0) supports Vanilla projects natively now. 

However, not all features we had in the temporary plugin are now available in ForgeGradle - unlike before it does not support merged client and server workspaces for Vanilla. Currently and for the foreseeable future not a big problem, however this means we need to **move all client code from SpongeCommon to SpongeForge**, as client code in SpongeCommon will no longer compile properly on SpongeVanilla after the upgrade.

---

This also brings us to the most important downside of keeping SpongeCommon in a source set in our implementations. The reason why the initial design had a separate Minecraft workspace was mostly to ensure SpongeCommon stays free from Forge code, because all the fields and methods added silently to Minecraft by Forge weren't even visible in SpongeCommon. If we make SpongeCommon a source set, you will still have the full Forge environment while working on SpongeCommon.

With the changes required to the SpongeVanilla workspace this is even a bit more difficult now:

**SpongeForge:**
- Forge adds new methods and fields to Minecraft classes - while working on SpongeCommon you need to check you're not actually using one of them. It will compile fine on SpongeForge - but as soon it is pushed to master and SpongeVanilla updates it will break.
- Client classes/methods/fields - this is easier, in the Forge environment they're marked with `@SideOnly(Side.CLIENT)` so it should be easier to prevent using them in SpongeCommon.

**SpongeVanilla:**
- Dedicated server-only classes/methods/fields - because the workspace is no longer merged client/server classes/methods only available on the server are no longer marked with `@SideOnly(Side.SERVER)` - these will compile fine in both implementations but will break as soon SpongeForge is installed on the client.

We will definitely need to keep SpongeCommon a Gradle project (though not directly used while working within one of the implementations) so we can have Travis build SpongeCommon to ensure it will be always compilable on both implementations.

---

Regarding the submodule setup: adding a new task to Gradle that will keep the submodule up-to-date and warn if not should be quite easy - I have a [similar task in a Gradle plugin I made](https://github.com/Minecrell/gitpatcher/blob/master/src/main/groovy/net/minecrell/gitpatcher/task/UpdateSubmodulesTask.groovy), it should be easy to get it into the Sponge build system. Staying with submodules is probably the best way for now that will still allow us enough control for example to use different versions of SpongeCommon in both implementations while still keeping the effort for development low.

---

I've updated the issue description with a TODO list to track the progress on the changes.

**Comment by JBYoshi** [comment]
Would it be possible to choose either to share a Minecraft JAR between common and Forge/vanilla or to have two separate ones?

**Comment by Minecrell** [comment]
@JBYoshi It would be probably _theoretically_ possible; however it would mess and complicate the build system setup even more than it's already now. Most people contributing would most likely use the first (and therefore recommended) option anyway so at the end it would probably not help much.

**Comment by Zidane** [comment]
@Minecrell 

I've checked a few entries off on this list above for you. Lets get some tracking going on finishing up the rename and the rest of the entries.

**Comment by JBYoshi** [comment]
@Zidane 
> I'm aware I said that we would merge back into one repo. After thinking about it and hearing both sides, it would fix some issues but bring about new ones that would go against the spirit of this project (and definitely against Vanilla).

You neglected to mention what issues you discussed. What issues would submodules fix, and what issues would they create?

**Comment by Minecrell** [comment]
Closing this, I've opened #214, #215 and SpongePowered/SpongeForge#377 for the remaining things to be done.
