### ISSUE TITLE
feature/redstone-tracking Issues

### ISSUE THREAD

**Issue by Faithcaio** [SpongePowered/SpongeCommon#244]
Console Output generated with: http://pastie.org/private/7dx06c550clnpwuigt8sw
- [x] http://puu.sh/l9zIo/2f19c7215c.jpg Pressing the left button causes weird stuff to happen: http://pastie.org/pastes/10529962/text?key=ofvodjezrdmv2xxzsshhla (Playercause is always there)
   - 1st event Buttonpress Ok
   - 2nd event Piston extend part 1 (wtf why is there an ItemFrame???)
   - 3rd event Piston extend part 2 (wtf why is there an ItemFrame???)
   - 4th event Piston extend part 3 / 5&6th event Button release and Piston retract (no Itemframe in cause)
-  [ ] http://puu.sh/l9CgZ/4ebd4b530f.jpg http://pastie.org/private/ukw6osliscbtedhs9nniw
   - 2nd and 3rd event: The block that got changed is listed as cause ; expected the lever or only player here

Minecart related: (http://puu.sh/l9vUR/70485aa623.jpg)
- [x] Detector Rail deactivation has no Player in Cause: http://pastie.org/private/f2xbgra2aosxncrbenxrcq
- [x] Place Minecart => Restart => Ride in Minecart => no Player in Cause: http://pastie.org/private/wfgysj8rehneozkk58jng (works on server)

**Comment by bloodmc** [comment]
@Faithcaio Please test the following again

Detector Rail deactivation
Placing minecart/restart

**Comment by Zidane** [comment]
[] Tossing an item into a hopper doesn't transfer the notifier from the EntityItem to the hopper.

[] Owner/notifier sometimes doesn't transfer onto Minecart Chest entities and therefore doesn't transfer to blocks that entity notifies.

**Comment by Zidane** [comment]
Redstone tracking is in master. Create new issues if bugs crop up.
