### ISSUE TITLE
DamageEntityEvent Checklist

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeCommon#282]
- [x] Throw DamageEntityEvents for all damage calls
- [x] Write Armor modification function implementation for both forge and vanilla
- [x] Associated DamageSources with "associated" objects in a `Cause`
 - [ ] Associated weapons for "Attack" causes
 - [x] Associated Entity owners with `EntityDamageSource`s
 - [x] Test with Thaumcraft
- [ ] Write Attack modifiers
- [x] Test Absorption modifier and handling

Anything else I'm missing?

**Comment by simon816** [comment]
Need to fire event for non-living entities, https://forums.spongepowered.org/t/no-destroying-item-frame/10093/7?u=simon816

**Comment by kashike** [comment]
In my opinion, there should be `DamageEntityEvent.Living` and `DamageEntityEvent.NonLiving`, or some other distinction other than the `Cause`.
