### ISSUE TITLE
SpawnCause Implementation Checklist

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeCommon#471]
- [ ] Fix block container breaks not providing the appropriate spawn cause
- [ ] Fix entity destruction handling
- [ ] Clean up capturing of entity spawns so that if the vanilla handling is used explicitly, allow it with it's special cause
- [ ] Refactor out entity spawn capturing from `MixinWorld.handlePostTickCaptures`

I'm sure there are other issues at large, but these are the ones that keep cropping up.
