### ISSUE TITLE
[1.9.4] Data Implementation Checklist

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeCommon#561]
Opening a checklist to note of the various changes that have taken place that need to be implemented for 1.9 full functionality.
- [x] PotionData available from Tipped Arrows
- [x] PotionData available from new Potion items (Splash potions and Lingering Potions)
- [x] Potion data implementation to solely focus based on NBT stored potions or try to pre-process them through the converters
- [x] PassengerData implementation
- [x] SkullHead implementation to allow adding dragon heads
- [x] Validate that all block related data is still functional (have to iterate through every combination of possibilities to make sure the blocks are still valid)
- [x] Add new Purpur block related data.
- [x] Remove Splash potion specific data as it's now it's own item.
- [x] Bump Entity content versions to note of the various changes in new keys used in NBT etc.
- [x] Bump ItemStack content versions for those that have changed

I'm sure there are more that I'm missing: If there are any, please comment and I'll add them to this list.

**Comment by gabizou** [comment]
Encourage the `ItemStackBuilder` to pass the `NBTTagCompound` through the data fixers to update content.
